topics:
  - name: AI Agents
    keywords: ["ai agents", "autonomous ai", "agentic workflows", "openai auto agents"]

  - name: SaaS Growth
    keywords: ["saas scaling", "bootstrapped startups", "product led growth"]

  - name: Indie Hacking
    keywords: ["indie hackers", "solo founders", "indie startup growth"]