name: Run AI Digest Agent Daily

on:
  schedule:
    - cron: '0 3 * * *' # Runs every day at 3 AM UTC
  workflow_dispatch: # Allows manual trigger too

jobs:
  run-digest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Digest Generator
      env:
        SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        RUN_ENV: cloud
        PYTHONPATH: ${{ github.workspace }}
      run: |
        python orchestrator/run_pipeline.py

    - name: Commit and Push Output
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add outputs/
        git commit -m "Daily Digest Update - $(date)"
        git push
      continue-on-error: true