name: Run AI Digest Agent Daily

on:
  schedule:
    - cron: '0 3 * * *' # Runs every day at 3 AM UTC
  workflow_dispatch: # Allows manual trigger too

jobs:
  run-digest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Digest Generator
      env:
        SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        RUN_ENV: cloud
        PYTHONPATH: ${{ github.workspace }}
      run: |
        python orchestrator/run_pipeline.py

    - name: Commit and Push Output
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add outputs/
        git commit -m "Daily Digest Update - $(date)" || echo "No changes to commit"
        git push
      continue-on-error: true
      
    - name: Copy to GitHub Pages branch
      run: |
        mkdir -p publish
        # Find all digest files
        DIGEST_FILES=$(ls outputs/digest-*.md | sort)

        # Find latest file
        LATEST_FILE=$(echo "$DIGEST_FILES" | tail -n 1)
        LATEST_BASENAME=$(basename "$LATEST_FILE")

        # Create index.md
        echo "# 📰 AI Digest Portal" > publish/index.md
        echo "" >> publish/index.md
        echo "## 📅 Archive" >> publish/index.md

        for f in $DIGEST_FILES; do
          fname=$(basename "$f")
          echo "- [${fname%.md}]($fname)" >> publish/index.md
        done

        echo "" >> publish/index.md
        echo "---" >> publish/index.md
        echo "## 🧠 Latest Digest" >> publish/index.md
        echo "" >> publish/index.md
        cat "$LATEST_FILE" >> publish/index.md

        # Copy digest files to publish dir
        cp outputs/digest-*.md publish/

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: publish